An error occured with the update: Error: Can't subset columns that don't exist.
[31mx[39m Column `Date` doesn't exist.
 on 2021-10-27 

An error occured with the update: Error in open.connection(structure(3L, class = c("curl", "connection"), conn_id = <pointer: 0x47c>), : HTTP error 404.
 on 2021-12-13 

